name: whereami
version: ${project.version}
author: jkm
main: dev.jkm.whereami.WhereAmIPlugin
api-version: 1.14

commands:
  whereami:
    description: Get the current zone you are in
    usage: /whereami